include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Only the most critical error rules
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    no_duplicate_case_values: true

    # Minimal style rules
    annotate_overrides: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    library_names: true

analyzer:
  errors:
    # Downgrade most lints to ignore
    always_use_package_imports: ignore
    avoid_print: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    prefer_single_quotes: ignore
    sort_pub_dependencies: ignore
    sort_constructors_first: ignore
    unnecessary_const: ignore
    unnecessary_this: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    unnecessary_null_comparison: ignore
    unused_import: ignore
    
    # Downgrade other common issues to info
    prefer_final_fields: info
    prefer_final_locals: info
    
    # Allow TODOs in the code
    todo: ignore
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
