workflows:
  android-workflow:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Add the group environment variables in Codemagic UI (e.g. ANDROID_KEYSTORE_PASSWORD, etc)
        - keystore_credentials
        - google_play_credentials
        - firebase_credentials
      vars:
        PACKAGE_NAME: "com.pinewraps.app"
        GOOGLE_PLAY_TRACK: "internal" # Available options: internal, alpha, beta, production
      flutter: stable
    scripts:
      - name: Set up keystore
        script: |
          echo $ANDROID_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          # Create key.properties file
          cat >> "$CM_BUILD_DIR/pinewraps_app/android/key.properties" << EOF
          storeFile=$CM_BUILD_DIR/keystore.jks
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          keyPassword=$ANDROID_KEY_PASSWORD
          EOF
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/pinewraps_app
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd $CM_BUILD_DIR/pinewraps_app
          flutter analyze
      - name: Build AAB
        script: |
          cd $CM_BUILD_DIR/pinewraps_app
          flutter build appbundle --release
    artifacts:
      - pinewraps_app/build/app/outputs/bundle/release/app-release.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false
      email:
        recipients:
          - your-email@example.com # Replace with your email

  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Add the group environment variables in Codemagic UI (e.g. APP_STORE_CONNECT_PRIVATE_KEY, etc)
        - app_store_credentials
        - firebase_credentials
      vars:
        BUNDLE_ID: "com.pinewraps.app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          cd $CM_BUILD_DIR/pinewraps_app/ios
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/pinewraps_app
          flutter packages pub get
      - name: Install CocoaPods
        script: |
          cd $CM_BUILD_DIR/pinewraps_app/ios
          pod install
      - name: Flutter analyze
        script: |
          cd $CM_BUILD_DIR/pinewraps_app
          flutter analyze
      - name: Build iOS app
        script: |
          cd $CM_BUILD_DIR/pinewraps_app
          flutter build ipa --release \
            --export-options-plist=$CM_BUILD_DIR/pinewraps_app/ios/ExportOptions.plist
    artifacts:
      - pinewraps_app/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - your-email@example.com # Replace with your email
