workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        IOS_BUNDLE_ID: "com.pinewraps.app"
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing"
          # Create temporary keychain
          keychain initialize
          
          # Check if we have App Store Connect API credentials
          if [ -n "$APP_STORE_CONNECT_ISSUER_ID" ] && [ -n "$APP_STORE_CONNECT_KEY_IDENTIFIER" ] && [ -n "$APP_STORE_CONNECT_PRIVATE_KEY" ]; then
            echo "Using App Store Connect API for code signing"
            app-store-connect fetch-signing-files "$IOS_BUNDLE_ID" --type IOS_APP_STORE --create
            keychain add-certificates
          else
            echo "App Store Connect API credentials not found. Using manual code signing."
            # Try to use certificate from environment variable
            if [ -n "$CERTIFICATE" ] && [ -n "$CERTIFICATE_PASSWORD" ]; then
              echo "Using certificate from environment variables"
              echo $CERTIFICATE | base64 --decode > $FCI_BUILD_DIR/certificate.p12
              keychain add-certificates --certificate $FCI_BUILD_DIR/certificate.p12 --certificate-password $CERTIFICATE_PASSWORD
            else
              echo "No code signing credentials found. Build may fail."
            fi
          fi
          
          # Set up provisioning profile
          xcode-project use-profiles
          
          # Set up Firebase configuration if needed
          if [ -n "$IOS_FIREBASE_CONFIG" ]; then
            echo "Setting up Firebase configuration"
            mkdir -p $FCI_BUILD_DIR/ios/Runner
            echo $IOS_FIREBASE_CONFIG | base64 --decode > $FCI_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          fi
          
      - name: Run iOS prebuild script
        script: |
          echo "Running iOS prebuild script"
          chmod +x $FCI_BUILD_DIR/ios_prebuild.sh
          $FCI_BUILD_DIR/ios_prebuild.sh
          
      - name: Flutter build iOS
        script: |
          cd $FCI_BUILD_DIR
          flutter build ios --release
          
      - name: Create IPA
        script: |
          cd $FCI_BUILD_DIR/ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
      
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        ANDROID_KEYSTORE: $ANDROID_KEYSTORE
        ANDROID_KEYSTORE_PASSWORD: $ANDROID_KEYSTORE_PASSWORD
        ANDROID_KEY_ALIAS: $ANDROID_KEY_ALIAS
        ANDROID_KEY_PASSWORD: $ANDROID_KEY_PASSWORD
        ANDROID_FIREBASE_CONFIG: $ANDROID_FIREBASE_CONFIG
    scripts:
      - name: Set up keystore
        script: |
          echo "Setting up Android keystore"
          echo $ANDROID_KEYSTORE | base64 --decode > $FCI_BUILD_DIR/keystore.jks
          
          # Create key.properties file
          cat >> "$FCI_BUILD_DIR/android/key.properties" << EOF
          storeFile=$FCI_BUILD_DIR/keystore.jks
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          keyPassword=$ANDROID_KEY_PASSWORD
          EOF
          
          # Set up Firebase configuration if needed
          if [ -n "$ANDROID_FIREBASE_CONFIG" ]; then
            echo "Setting up Firebase configuration"
            mkdir -p $FCI_BUILD_DIR/android/app
            echo $ANDROID_FIREBASE_CONFIG | base64 --decode > $FCI_BUILD_DIR/android/app/google-services.json
          fi
          
      - name: Flutter build APK and AppBundle
        script: |
          cd $FCI_BUILD_DIR
          # Uncomment the following line if you need to build a specific flavor
          # flutter build apk --release --flavor production
          flutter build apk --release
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
      
  # Combined workflow that builds both iOS and Android
  combined-workflow:
    name: iOS and Android Build
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        IOS_BUNDLE_ID: "com.pinewraps.app"
        IOS_FIREBASE_CONFIG: $IOS_FIREBASE_CONFIG
        ANDROID_KEYSTORE: $ANDROID_KEYSTORE
        ANDROID_KEYSTORE_PASSWORD: $ANDROID_KEYSTORE_PASSWORD
        ANDROID_KEY_ALIAS: $ANDROID_KEY_ALIAS
        ANDROID_KEY_PASSWORD: $ANDROID_KEY_PASSWORD
        ANDROID_FIREBASE_CONFIG: $ANDROID_FIREBASE_CONFIG
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    scripts:
      # iOS setup and build
      - name: Set up iOS code signing
        script: |
          echo "Setting up iOS code signing"
          keychain initialize
          
          # Check if we have App Store Connect API credentials
          if [ -n "$APP_STORE_CONNECT_ISSUER_ID" ] && [ -n "$APP_STORE_CONNECT_KEY_IDENTIFIER" ] && [ -n "$APP_STORE_CONNECT_PRIVATE_KEY" ]; then
            echo "Using App Store Connect API for code signing"
            app-store-connect fetch-signing-files "$IOS_BUNDLE_ID" --type IOS_APP_STORE --create
            keychain add-certificates
          else
            echo "App Store Connect API credentials not found. Using manual code signing."
            # Try to use certificate from environment variable
            if [ -n "$CERTIFICATE" ] && [ -n "$CERTIFICATE_PASSWORD" ]; then
              echo "Using certificate from environment variables"
              echo $CERTIFICATE | base64 --decode > $FCI_BUILD_DIR/certificate.p12
              keychain add-certificates --certificate $FCI_BUILD_DIR/certificate.p12 --certificate-password $CERTIFICATE_PASSWORD
            else
              echo "No code signing credentials found. Build may fail."
            fi
          fi
          
          xcode-project use-profiles
          
          # Set up Firebase configuration if needed
          if [ -n "$IOS_FIREBASE_CONFIG" ]; then
            mkdir -p $FCI_BUILD_DIR/ios/Runner
            echo $IOS_FIREBASE_CONFIG | base64 --decode > $FCI_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          fi
          
      - name: Run iOS prebuild script
        script: |
          echo "Running iOS prebuild script"
          chmod +x $FCI_BUILD_DIR/ios_prebuild.sh
          $FCI_BUILD_DIR/ios_prebuild.sh
          
      - name: Flutter build iOS
        script: |
          cd $FCI_BUILD_DIR
          flutter build ios --release
          
      - name: Create iOS IPA
        script: |
          cd $FCI_BUILD_DIR/ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios/ipa
          
      # Android setup and build
      - name: Set up Android keystore
        script: |
          echo "Setting up Android keystore"
          echo $ANDROID_KEYSTORE | base64 --decode > $FCI_BUILD_DIR/keystore.jks
          
          # Create key.properties file
          cat >> "$FCI_BUILD_DIR/android/key.properties" << EOF
          storeFile=$FCI_BUILD_DIR/keystore.jks
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          keyPassword=$ANDROID_KEY_PASSWORD
          EOF
          
          # Set up Firebase configuration if needed
          if [ -n "$ANDROID_FIREBASE_CONFIG" ]; then
            mkdir -p $FCI_BUILD_DIR/android/app
            echo $ANDROID_FIREBASE_CONFIG | base64 --decode > $FCI_BUILD_DIR/android/app/google-services.json
          fi
          
      - name: Flutter build Android
        script: |
          cd $FCI_BUILD_DIR
          flutter build apk --release
          flutter build appbundle --release
          
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
