// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the available platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYspB4HlxdCC6qLcpmiTjaEaiRiDcq16A',
    appId: '1:181991178384:web:a5699293807394f7485815',
    messagingSenderId: '181991178384',
    projectId: 'pinewraps-23e8a',
    authDomain: 'pinewraps-23e8a.firebaseapp.com',
    storageBucket: 'pinewraps-23e8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYspB4HlxdCC6qLcpmiTjaEaiRiDcq16A',
    appId: '1:181991178384:android:a5699293807394f7485815',
    messagingSenderId: '181991178384',
    projectId: 'pinewraps-23e8a',
    storageBucket: 'pinewraps-23e8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYspB4HlxdCC6qLcpmiTjaEaiRiDcq16A',
    appId: '1:181991178384:ios:a5699293807394f7485815',
    messagingSenderId: '181991178384',
    projectId: 'pinewraps-23e8a',
    storageBucket: 'pinewraps-23e8a.appspot.com',
    iosClientId: '181991178384-ios.apps.googleusercontent.com',
    iosBundleId: 'com.pinewraps.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYspB4HlxdCC6qLcpmiTjaEaiRiDcq16A',
    appId: '1:181991178384:macos:a5699293807394f7485815',
    messagingSenderId: '181991178384',
    projectId: 'pinewraps-23e8a',
    storageBucket: 'pinewraps-23e8a.appspot.com',
    iosClientId: '181991178384-macos.apps.googleusercontent.com',
    iosBundleId: 'com.pinewraps.app.macos',
  );
}
