platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Define static framework pods
$static_framework = ['FirebaseCore',
                    'FirebaseMessaging',
                    'Firebase',
                    'FirebaseCoreInternal',
                    'GoogleUtilities',
                    'nanopb']

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! 
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Force Firebase pods to be static
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
end

post_install do |installer|
  # Fix for Xcode 15
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Add Flutter header search paths
      config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited)'
      config.build_settings['HEADER_SEARCH_PATHS'] += ' "${PODS_ROOT}/Headers/Public/Flutter"'
      config.build_settings['HEADER_SEARCH_PATHS'] += ' "${PODS_ROOT}/../Flutter"'
      config.build_settings['HEADER_SEARCH_PATHS'] += ' "${PODS_CONFIGURATION_BUILD_DIR}/Flutter-framework"'
      config.build_settings['HEADER_SEARCH_PATHS'] += ' "${PODS_CONFIGURATION_BUILD_DIR}/Flutter"'

      # Fix for arm64 architecture
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
      # Fix Firebase modular headers issue
      if $static_framework.include?(target.name)
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        
        # Additional Firebase settings
        config.build_settings['OTHER_LDFLAGS'] ||= '$(inherited)'
        config.build_settings['OTHER_LDFLAGS'] += ' -ObjC'
        
        # Ensure Firebase headers are found
        config.build_settings['HEADER_SEARCH_PATHS'] += ' "${PODS_ROOT}/Firebase/CoreOnly/Sources"'
        config.build_settings['HEADER_SEARCH_PATHS'] += ' "${PODS_TARGET_SRCROOT}"'
      end
    end
  end
end
